// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tictactoe/tictactoe/completed_game.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CompletedGame struct {
	Index   string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Board   string `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	PlayerX string `protobuf:"bytes,3,opt,name=playerX,proto3" json:"playerX,omitempty"`
	PlayerO string `protobuf:"bytes,4,opt,name=playerO,proto3" json:"playerO,omitempty"`
	Winner  string `protobuf:"bytes,5,opt,name=winner,proto3" json:"winner,omitempty"`
}

func (m *CompletedGame) Reset()         { *m = CompletedGame{} }
func (m *CompletedGame) String() string { return proto.CompactTextString(m) }
func (*CompletedGame) ProtoMessage()    {}
func (*CompletedGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b8dadfa59c4d88f, []int{0}
}
func (m *CompletedGame) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CompletedGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CompletedGame.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CompletedGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompletedGame.Merge(m, src)
}
func (m *CompletedGame) XXX_Size() int {
	return m.Size()
}
func (m *CompletedGame) XXX_DiscardUnknown() {
	xxx_messageInfo_CompletedGame.DiscardUnknown(m)
}

var xxx_messageInfo_CompletedGame proto.InternalMessageInfo

func (m *CompletedGame) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *CompletedGame) GetBoard() string {
	if m != nil {
		return m.Board
	}
	return ""
}

func (m *CompletedGame) GetPlayerX() string {
	if m != nil {
		return m.PlayerX
	}
	return ""
}

func (m *CompletedGame) GetPlayerO() string {
	if m != nil {
		return m.PlayerO
	}
	return ""
}

func (m *CompletedGame) GetWinner() string {
	if m != nil {
		return m.Winner
	}
	return ""
}

func init() {
	proto.RegisterType((*CompletedGame)(nil), "sudhakarmamillapalli.tictactoe.tictactoe.CompletedGame")
}

func init() {
	proto.RegisterFile("tictactoe/tictactoe/completed_game.proto", fileDescriptor_6b8dadfa59c4d88f)
}

var fileDescriptor_6b8dadfa59c4d88f = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x28, 0xc9, 0x4c, 0x2e,
	0x49, 0x4c, 0x2e, 0xc9, 0x4f, 0xd5, 0x47, 0xb0, 0x92, 0xf3, 0x73, 0x0b, 0x72, 0x52, 0x4b, 0x52,
	0x53, 0xe2, 0xd3, 0x13, 0x73, 0x53, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x34, 0x8a, 0x4b,
	0x53, 0x32, 0x12, 0xb3, 0x13, 0x8b, 0x72, 0x13, 0x73, 0x33, 0x73, 0x72, 0x12, 0x0b, 0x12, 0x73,
	0x72, 0x32, 0xf5, 0xe0, 0x9a, 0x10, 0x2c, 0xa5, 0x76, 0x46, 0x2e, 0x5e, 0x67, 0x98, 0x11, 0xee,
	0x89, 0xb9, 0xa9, 0x42, 0x22, 0x5c, 0xac, 0x99, 0x79, 0x29, 0xa9, 0x15, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x10, 0x0e, 0x48, 0x34, 0x29, 0x3f, 0xb1, 0x28, 0x45, 0x82, 0x09, 0x22, 0x0a,
	0xe6, 0x08, 0x49, 0x70, 0xb1, 0x17, 0xe4, 0x24, 0x56, 0xa6, 0x16, 0x45, 0x48, 0x30, 0x83, 0xc5,
	0x61, 0x5c, 0x84, 0x8c, 0xbf, 0x04, 0x0b, 0xb2, 0x8c, 0xbf, 0x90, 0x18, 0x17, 0x5b, 0x79, 0x66,
	0x5e, 0x5e, 0x6a, 0x91, 0x04, 0x2b, 0x58, 0x02, 0xca, 0x73, 0x0a, 0x3b, 0xf1, 0x48, 0x8e, 0xf1,
	0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e,
	0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0x9b, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc,
	0x5c, 0x7d, 0x98, 0xc7, 0x74, 0x91, 0x7d, 0x86, 0x14, 0x1c, 0x15, 0x48, 0xec, 0x92, 0xca, 0x82,
	0xd4, 0xe2, 0x24, 0x36, 0x70, 0x90, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x87, 0xb5, 0x59,
	0x8a, 0x3e, 0x01, 0x00, 0x00,
}

func (m *CompletedGame) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CompletedGame) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CompletedGame) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Winner) > 0 {
		i -= len(m.Winner)
		copy(dAtA[i:], m.Winner)
		i = encodeVarintCompletedGame(dAtA, i, uint64(len(m.Winner)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PlayerO) > 0 {
		i -= len(m.PlayerO)
		copy(dAtA[i:], m.PlayerO)
		i = encodeVarintCompletedGame(dAtA, i, uint64(len(m.PlayerO)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PlayerX) > 0 {
		i -= len(m.PlayerX)
		copy(dAtA[i:], m.PlayerX)
		i = encodeVarintCompletedGame(dAtA, i, uint64(len(m.PlayerX)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Board) > 0 {
		i -= len(m.Board)
		copy(dAtA[i:], m.Board)
		i = encodeVarintCompletedGame(dAtA, i, uint64(len(m.Board)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintCompletedGame(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCompletedGame(dAtA []byte, offset int, v uint64) int {
	offset -= sovCompletedGame(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CompletedGame) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovCompletedGame(uint64(l))
	}
	l = len(m.Board)
	if l > 0 {
		n += 1 + l + sovCompletedGame(uint64(l))
	}
	l = len(m.PlayerX)
	if l > 0 {
		n += 1 + l + sovCompletedGame(uint64(l))
	}
	l = len(m.PlayerO)
	if l > 0 {
		n += 1 + l + sovCompletedGame(uint64(l))
	}
	l = len(m.Winner)
	if l > 0 {
		n += 1 + l + sovCompletedGame(uint64(l))
	}
	return n
}

func sovCompletedGame(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCompletedGame(x uint64) (n int) {
	return sovCompletedGame(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CompletedGame) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompletedGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CompletedGame: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CompletedGame: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompletedGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompletedGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompletedGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Board", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompletedGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompletedGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompletedGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Board = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerX", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompletedGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompletedGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompletedGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlayerX = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerO", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompletedGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompletedGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompletedGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlayerO = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Winner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompletedGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompletedGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompletedGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Winner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCompletedGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCompletedGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCompletedGame(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCompletedGame
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCompletedGame
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCompletedGame
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCompletedGame
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCompletedGame
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCompletedGame
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCompletedGame        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCompletedGame          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCompletedGame = fmt.Errorf("proto: unexpected end of group")
)
